version: '3.7'

services:
  generate-ssl:
    image: alpine/openssl
    container_name: generate-ssl
    volumes:
      - ./data/ssl:/ssl
    entrypoint: >
      sh -c "openssl req -x509 -nodes -days 365 -newkey rsa:2048 
      -keyout /ssl/the.key -out /ssl/the.crt -subj '/C=US/ST=State/L=City/O=Organization/OU=Department/CN=olm.local' && 
      cat /ssl/the.crt /ssl/the.key > /ssl/the.pem"

  api:
    extends:
      file: docker-compose.yaml
      service: api
    depends_on:
      generate-ssl:
        condition: service_completed_successfully
