version: '3.7'

services:
  api:
    image: hamidmayeli/olm:latest
    container_name: api
    restart: always
    volumes:
      - ./data/db:/data
      - ./data/ssl:/ssl
      - ./data/keys:/root/.aspnet/DataProtection-Keys
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/ssl/the.pem
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/ssl/the.key
      - ALLOWEDHOSTS=${DOMAIN}
    ports:
      - 80:80
      - 443:443
